namespace Util.Tools.Offices.Core {
    /// <summary>
    /// 颜色
    /// </summary>
    public enum Color {
        Black, 
        Brown, 
        OliveGreen, 
        DarkGreen,
        DarkTeal, 
        DarkBlue, 
        Indigo, 
        Grey80Percent,
        Orange, 
        DarkYellow, 
        Green, 
        Teal, 
        Blue,
        BlueGrey, 
        Grey50Percent, 
        Red, 
        LightOrange, 
        Lime,
        SeaGreen, 
        Aqua, 
        LightBlue, 
        Violet, 
        Grey40Percent,
        Pink, 
        Gold, 
        Yellow, 
        BrightGreen, 
        Turquoise,
        DarkRed, 
        SkyBlue, 
        Plum, 
        Grey25Percent, 
        Rose,
        LightYellow, 
        LightGreen, 
        LightTurquoise, 
        PaleBlue,
        Lavender, 
        White, 
        CornflowerBlue, 
        LemonChiffon,
        Maroon, 
        Orchid, 
        Coral, 
        RoyalBlue,
        LightCornflowerBlue, 
        Tan
    }
}
