global using System;
global using System.Threading.Tasks;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Data;
global using System.Collections.Concurrent;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Npgsql;