//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Util.Security.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SecurityResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecurityResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Util.Security.Properties.SecurityResource", typeof(SecurityResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 应用程序编码 {0} 已存在 的本地化字符串。
        /// </summary>
        public static string DuplicateApplicationCode {
            get {
                return ResourceManager.GetString("DuplicateApplicationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用程序名称 {0} 已存在 的本地化字符串。
        /// </summary>
        public static string DuplicateApplicationName {
            get {
                return ResourceManager.GetString("DuplicateApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮件 {0} 已存在 的本地化字符串。
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色编码 {0} 已存在 的本地化字符串。
        /// </summary>
        public static string DuplicateRoleCode {
            get {
                return ResourceManager.GetString("DuplicateRoleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名 {0} 已存在 的本地化字符串。
        /// </summary>
        public static string DuplicateRoleName {
            get {
                return ResourceManager.GetString("DuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 {0} 已存在 的本地化字符串。
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帐号无效或密码不正确 的本地化字符串。
        /// </summary>
        public static string InvalidAccountOrPassword {
            get {
                return ResourceManager.GetString("InvalidAccountOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮件无效或密码不正确 的本地化字符串。
        /// </summary>
        public static string InvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("InvalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号无效或密码不正确 的本地化字符串。
        /// </summary>
        public static string InvalidPhoneOrPassword {
            get {
                return ResourceManager.GetString("InvalidPhoneOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 {0} 无效 的本地化字符串。
        /// </summary>
        public static string InvalidRoleName {
            get {
                return ResourceManager.GetString("InvalidRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的令牌 的本地化字符串。
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 {0} 无效，仅允许字母或数字 的本地化字符串。
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名无效或密码不正确 的本地化字符串。
        /// </summary>
        public static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由于您多次登录失败，暂时被系统锁定，请稍后再试 的本地化字符串。
        /// </summary>
        public static string LoginFailLock {
            get {
                return ResourceManager.GetString("LoginFailLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码错误 的本地化字符串。
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码应包含数字 的本地化字符串。
        /// </summary>
        public static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码应包含非字母和数字的特殊字符，比如 # 的本地化字符串。
        /// </summary>
        public static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码应包含至少 {0} 个不重复的字符 的本地化字符串。
        /// </summary>
        public static string PasswordRequiresUniqueChars {
            get {
                return ResourceManager.GetString("PasswordRequiresUniqueChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码应包含大写字母 的本地化字符串。
        /// </summary>
        public static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能少于 {0} 个字符 的本地化字符串。
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的帐户已被冻结，请联系管理员 的本地化字符串。
        /// </summary>
        public static string UserIsDisabled {
            get {
                return ResourceManager.GetString("UserIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不能为空 的本地化字符串。
        /// </summary>
        public static string UserNameIsEmpty {
            get {
                return ResourceManager.GetString("UserNameIsEmpty", resourceCulture);
            }
        }
    }
}
