//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Util.Biz.Payments.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PayResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PayResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Util.Biz.Payments.Properties.PayResource", typeof(PayResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 支付宝交易号和商户订单号不能同时为空 的本地化字符串。
        /// </summary>
        public static string AlipayCancelParamIsEmpty {
            get {
                return ResourceManager.GetString("AlipayCancelParamIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户付款授权码 的本地化字符串。
        /// </summary>
        public static string AuthCode {
            get {
                return ResourceManager.GetString("AuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户付款授权码不能为空 的本地化字符串。
        /// </summary>
        public static string AuthCodeIsEmpty {
            get {
                return ResourceManager.GetString("AuthCodeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支付金额必须大于0 的本地化字符串。
        /// </summary>
        public static string InvalidMoney {
            get {
                return ResourceManager.GetString("InvalidMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商户订单号不能为空 的本地化字符串。
        /// </summary>
        public static string OrderIdIsEmpty {
            get {
                return ResourceManager.GetString("OrderIdIsEmpty", resourceCulture);
            }
        }
    }
}
